# Generated by Django 3.2.2 on 2021-05-08 11:08

from django.db import migrations, models

import utils.func


class Migration(migrations.Migration):

    dependencies = [("product", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_code",
            field=models.CharField(
                default=utils.func.Utils.generate_prd_code, max_length=4
            ),
        )
    ]
